// ==========================================
// SHARED EVENTS DATABASE
// Used by both main.js and event-detail.js
// ==========================================

// All events with complete details
const sharedEventsData = [
    // KONSERLER (ID 1-25)
    { id: 1, name: "Tarkan - Yeni Albüm Turnesi", date: "2025-12-08", venue: "İstanbul - Volkswagen Arena", price: "₺750", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800", category: "Konser", description: "Türk Pop Müziğinin Megastarı Tarkan, yeni albümü '10' ile muhteşem bir konser deneyimi sunuyor! Şımarık, Kuzu Kuzu, Dudu gibi efsane hit şarkılarının yanı sıra yeni albümden ilk kez duyacağınız parçalar da sizi bekliyor.", features: ["3 saatlik canlı performans", "30+ hit şarkı", "Özel ışık ve lazer show", "VIP alanında özel ikramlar"], doorTime: "Konserden 2 saat önce", ageLimit: "+7 yaş", availability: 35 },
    { id: 2, name: "Sertab Erener - Evgit Gel", date: "2025-12-09", venue: "İzmir - İzmir Arena", price: "₺450", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800", category: "Konser", description: "Eurovision birincisi Sertab Erener, 'Everyway That I Can', 'Aşk', 'Kendime Yeni Bir Ben Lazım' gibi hit şarkılarıyla unutulmaz bir gece vaat ediyor.", features: ["Tüm hit şarkılar", "Eurovision performansı", "Özel romantik düzenlemeler", "2.5 saat canlı müzik"], doorTime: "Konserden 2 saat önce", ageLimit: "+12 yaş", availability: 42 },
    { id: 3, name: "Mabel Matiz Konseri", date: "2025-12-10", venue: "İstanbul - Bostancı", price: "₺550", image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800", category: "Konser", description: "Alternatif pop müziğin sevilen ismi Mabel Matiz, 'Gel', 'Yalan', 'Boyalı da Saçların' gibi parçalarıyla sahnede.", features: ["Alternatif pop performans", "Tüm popüler şarkılar", "Özel sahne tasarımı", "2 saat müzik şöleni"], doorTime: "Konserden 1.5 saat önce", ageLimit: "+10 yaş", availability: 48 },
    { id: 4, name: "Ajda Pekkan Gala", date: "2025-12-11", venue: "İstanbul - Harbiye", price: "₺1200", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", category: "Konser", description: "Türk pop müziğinin efsane ismi Ajda Pekkan, 50 yılı aşkın kariyerinin en sevilen şarkılarıyla özel bir gala konseri veriyor.", features: ["50+ yıllık kariyer şarkıları", "Özel gala düzenlemesi", "Görkemli sahne ve kostümler", "3 saatlik unutulmaz gece"], doorTime: "Gösterimden 2 saat önce", ageLimit: "+15 yaş", availability: 28 },
    { id: 5, name: "Sezen Aksu - 40 Yıl", date: "2025-12-12", venue: "İstanbul - TT Stadyumu", price: "₺900", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", category: "Konser", description: "Türk pop müziğinin Minik Serçesi Sezen Aksu, 40 yıllık müzik hayatını kutluyor. Efsanevi şarkılar, duygusal anlar ve muhteşem bir prodüksiyon.", features: ["40 yıllık kariyer retrospektifi", "50+ efsane şarkı", "Konuk sanatçılar", "Stadyum konseri deneyimi"], doorTime: "Konserden 3 saat önce", ageLimit: "Tüm yaşlar", availability: 52 },
    { id: 6, name: "Hadise - Aşk Turnesi", date: "2025-12-13", venue: "Antalya - Aspendos", price: "₺650", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800", category: "Konser", description: "Pop müziğin dinamik ismi Hadise, enerji dolu şarkıları ve sahne performansıyla Aspendos Antik Tiyatrosu'nda.", features: ["Antik tiyatroda özel konser", "Dance-pop performans", "Choreography show", "2 saat eğlence"], doorTime: "Konserden 2 saat önce", ageLimit: "+7 yaş", availability: 45 },
    { id: 7, name: "Kenan Doğulu Live", date: "2025-12-14", venue: "İstanbul - Jolly Joker", price: "₺400", image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800", category: "Konser", description: "Pop müziğin sevilen sesi Kenan Doğulu, 'Tencere Tava Havası', 'Aşk Olsun' gibi hit parçalarıyla intimate bir konser deneyimi sunuyor.", features: ["Yakın sahne deneyimi", "Akustik düzenlemeler", "Fan interaktif oturumu", "2.5 saat müzik"], doorTime: "Konserden 1 saat önce", ageLimit: "+12 yaş", availability: 38 },
    { id: 8, name: "Gülşen - Bangır Tour", date: "2025-12-15", venue: "Bodrum - Antik Tiyatro", price: "₺800", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", category: "Konser", description: "Pop müziğin iddialı sesi Gülşen, 'Bangır Bangır', 'Yatcaz Kalkcaz' gibi hit şarkılarıyla antik tiyatroda yaz konseri.", features: ["Bodrum özel konseri", "Summer vibes", "DJ set after party", "Deniz manzarası"], doorTime: "Konserden 2 saat önce", ageLimit: "+16 yaş", availability: 31 },
    { id: 9, name: "Sıla - Sahne Programı", date: "2025-12-16", venue: "Ankara - Congresium", price: "₺550", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", category: "Konser", description: "Türk pop müziğinin güçlü sesi Sıla, 'Yan Benimle', 'Afitap', 'Sevişmeden Uyumayalım' gibi duygusal şarkılarıyla sahnede.", features: ["Duygusal vokal performans", "Akustik band eşliği", "2.5 saat konser", "Özel repertuar"], doorTime: "Konserden 2 saat önce", ageLimit: "+12 yaş", availability: 42 },
    { id: 10, name: "Teoman - Akustik", date: "2025-12-17", venue: "İstanbul - Zorlu PSM", price: "₺600", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800", category: "Konser", description: "Rock ve alternatif müziğin öncü ismi Teoman, akustik düzenlemeleriyle en sevilen şarkılarını seslendiriyor.", features: ["Tam akustik performans", "İntimate sahne atmosferi", "Hikayelerle süslü şarkılar", "2 saat özel konser"], doorTime: "Gösterimden 1.5 saat önce", ageLimit: "+14 yaş", availability: 36 },
    { id: 11, name: "Nilüfer Konseri", date: "2025-12-18", venue: "Ankara - ATO", price: "₺500", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800", category: "Konser", description: "Türk pop müziğinin unutulmaz sesi Nilüfer, kariyerinin 40+ yılından en sevilen parçalarla sahnede.", features: ["40 yıllık hit şarkılar", "Klasik pop repertuar", "Nostaljik atmosfer", "2.5 saat müzik"], doorTime: "Konserden 2 saat önce", ageLimit: "Tüm yaşlar", availability: 44 },
    { id: 12, name: "Yıldız Tilbe Show", date: "2025-12-19", venue: "İstanbul - Harbiye", price: "₺700", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", category: "Konser", description: "Türk pop ve arabesk müziğin güçlü sesi Yıldız Tilbe, enerji dolu sahne performansıyla tüm hit şarkılarını seslendiriyor.", features: ["Enerji dolu performans", "Pop ve arabesk karışımı", "Sahne쇼wu", "3 saat konser"], doorTime: "Konserden 2 saat önce", ageLimit: "+12 yaş", availability: 40 },
    { id: 13, name: "Emre Aydın Live", date: "2025-12-20", venue: "İzmir - Kültürpark", price: "₺350", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", category: "Konser", description: "Alternatif rock'ın sevilen sesi Emre Aydın, 'Afili Yalnızlık', 'Hoşçakal' gibi şarkılarıyla sahnede.", features: ["Alternative rock performans", "Elektrik gitar soloları", "Melankol dolu şarkılar", "2 saat konser"], doorTime: "Konserden 1.5 saat önce", ageLimit: "+10 yaş", availability: 50 },
    { id: 14, name: "Fettah Can Akustik", date: "2025-12-21", venue: "Bursa - Merinos", price: "₺400", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800", category: "Konser", description: "Arabesk müziğin genç sesi Fettah Can, duygusal şarkılarını akustik düzenlemelerle seslendiriyor.", features: ["Akustik arabesk", "Duygusal repertuar", "Intimate atmosfer", "2 saat müzik"], doorTime: "Gösterimden 1 saat önce", ageLimit: "+12 yaş", availability: 46 },
    { id: 15, name: "Simge Konseri", date: "2025-12-22", venue: "Antalya - Expo", price: "₺450", image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800", category: "Konser", description: "Pop müziğin taze sesi Simge, 'Miş Miş', 'Yankı', 'Öpücem' gibi hit şarkılarıyla eğlence dolu bir gece vaat ediyor.", features: ["Genç pop energy", "Dance choreography", "Parti atmosferi", "2.5 saat eğlence"], doorTime: "Konserden 2 saat önce", ageLimit: "+7 yaş", availability: 48 },
    { id: 16, name: "Gripin Live", date: "2025-12-23", venue: "İstanbul - Küçükçiftlik", price: "₺350", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", category: "Konser", description: "Rock grubun sevilen sesi Gripin, 'Böyle Kahpedir Dünya', 'Durma Yağmur Durma' gibi enerjik şarkılarıyla sahnede.", features: ["Rock band performans", "Grup enerjisi", "Kalabalık etkileşimi", "2 saat rock"], doorTime: "Konserden 2 saat önce", ageLimit: "+10 yaş", availability: 52 },
    { id: 17, name: "Aleyna Tilki Konseri", date: "2025-12-24", venue: "İstanbul - IF Performance", price: "₺500", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", category: "Konser", description: "Genç pop yıldızı Aleyna Tilki, dinamik performansı ve hit şarkılarıyla gençlerin favorisi bir konser sunuyor.", features: ["Genç pop star", "Social media friendly", "Modern pop sound", "2 saat konser"], doorTime: "Konserden 1.5 saat önce", ageLimit: "+7 yaş", availability: 38 },
    { id: 18, name: "Gökhan Türkmen", date: "2025-12-25", venue: "Ankara - Bilkent", price: "₺400", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800", category: "Konser", description: "Rock ve pop'un sevilen sesi Gökhan Türkmen, duygusal baladları ve enerjik şarkılarıyla sahnede.", features: ["Rock-pop karışımı", "Vokal performans", "Gitar soloları", "2.5 saat müzik"], doorTime: "Konserden 2 saat önce", ageLimit: "+12 yaş", availability: 44 },
    { id: 19, name: "Oğuzhan Koç Konseri", date: "2025-12-26", venue: "İstanbul - Jolly Joker", price: "₺350", image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800", category: "Konser", description: "Pop müziğin sevilen ismi Oğuzhan Koç, 'Yanıyorum', 'Gözlerine' gibi romantin şarkılarıyla intimate bir konser.", features: ["Romantik pop", "Intimate venue", "Fan etkileşimi", "2 saat konser"], doorTime: "Konserden 1 saat önce", ageLimit: "+10 yaş", availability: 50 },
    { id: 20, name: "Hande Yener Show", date: "2025-12-27", venue: "Bodrum - Voyage", price: "₺600", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", category: "Konser", description: "Türk pop müziğin kraliçesi Hande Yener, 'Sopa', 'Acele Etme', 'Kibir' gibi efsane parçalarla lüks bir gece.", features: ["Pop diva performansı", "Lüks venue", "DJ set sonrası", "3 saat show"], doorTime: "Gösterimden 2 saat önce", ageLimit: "+18 yaş", availability: 32 },
    { id: 21, name: "Merve Özbey Live", date: "2025-12-28", venue: "İzmir - Arena", price: "₺450", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", category: "Konser", description: "Pop müziğin sevilen yorumcusu Merve Özbey, güçlü sesiyle duygusal şarkılar seslendiriyor.", features: ["Güçlü vokal", "Duygusal baladlar", "Modern pop sound", "2 saat müzik"], doorTime: "Konserden 2 saat önce", ageLimit: "+12 yaş", availability: 42 },
    { id: 22, name: "Demet Akalın Party", date: "2025-12-29", venue: "Antalya - Regnum", price: "₺700", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800", category: "Konser", description: "Pop-arabesk kraliçesi Demet Akalın, enerji dolu şarkıları ve şovuyla lüks bir yılbaşı öncesi parti.", features: ["Party atmosferi", "Lüks otel konser", "DJ performans", "Open bar (VIP)"], doorTime: "Partiden 2 saat önce", ageLimit: "+18 yaş", availability: 28 },
    { id: 23, name: "Ece Seçkin Konseri", date: "2025-12-30", venue: "İstanbul - Babylon", price: "₺400", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", category: "Konser", description: "Genç pop yıldızı Ece Seçkin, dans edilebilir şarkıları ve dinamik performansıyla yılın son günlerinde sahnede.", features: ["Dance-pop", "Choreo show", "Genç atmosfer", "2.5 saat eğlence"], doorTime: "Konserden 1.5 saat önce", ageLimit: "+10 yaş", availability: 46 },
    { id: 24, name: "Yılbaşı Konseri 2025", date: "2025-12-31", venue: "İstanbul - Harbiye", price: "₺1500", image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", category: "Konser", description: "Yılın son gecesi özel konseri - çok sayıda sanatçı, havai fişek gösterisi ve unutulmaz bir gece.", features: ["Çoklu sanatçı lineup", "Havai fişek gösterisi", "Gece yarısı kutlaması", "5+ saat program"], doorTime: "Gösterimden 3 saat önce", ageLimit: "+18 yaş", availability: 18 },
    { id: 25, name: "Tarkan Yılbaşı", date: "2026-01-01", venue: "Antalya - Belek", price: "₺2000", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800", category: "Konser", description: "Türk popun megastarı Tarkan ile yeni yıla özel lüks otel konseri - şampanya, gala yemeği ve unutulmaz performans.", features: ["Gala yemeği dahil", "Lüks otel konseri", "Şampanya ikramı", "4 saat özel program"], doorTime: "Akşam yemeğinden 1 saat önce", ageLimit: "+21 yaş", availability: 12 },

    // ROCK (ID 26-40)
    { id: 26, name: "Duman - 25. Yıl", date: "2025-12-08", venue: "İstanbul - Küçükçiftlik", price: "₺700", image: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800", category: "Rock", description: "Türk rock'ın efsane grubu Duman, 25. yıl özel konseriyle 'Helal Olsun', 'Her Şeyi Yak', 'Senden Daha Güzel' gibi şarkılarını çalıyor.", features: ["25 yıllık kariyer kutlaması", "Tüm klasik hitler", "Özel sahne tasarımı", "3 saat rock"], doorTime: "Konserden 2 saat önce", ageLimit: "+14 yaş", availability: 30 },
    { id: 27, name: "Mor ve Ötesi", date: "2025-12-10", venue: "İzmir - Kültürpark", price: "₺400", image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800", category: "Rock", description: "Alternative rock'ın öncü grubu Mor ve Ötesi, 'Bir Derdim Var', 'Cambaz' gibi enerjik parçalarla sahnede.", features: ["Alternative rock", "Grup enerjisi", "Gitar Performance", "2.5 saat konser"], doorTime: "Konserden 2 saat önce", ageLimit: "+12 yaş", availability: 48 },
    { id: 28, name: "Athena Rock Fest", date: "2025-12-12", venue: "İstanbul - Parkorman", price: "₺350", image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800", category: "Rock", description: "Ska-punk grubu Athena, yüksek tempolu şarkıları ve sahne enerjisiyle açık hava konseri veriyor.", features: ["Ska-punk energy", "Açık hava festivali", "Brass section", "2 saat show"], doorTime: "Festivalden 1.5 saat önce", ageLimit: "+10 yaş", availability: 55 },
    { id: 29, name: "Şebnem Ferah", date: "2025-12-14", venue: "Bursa - Açık Hava", price: "₺450", image: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800", category: "Rock", description: "Türk rock'ın güçlü kadın sesi Şebnem Ferah, 'Sil Baştan', 'Vazgeçmem Dünyada' gibi şarkılarla sahne alıyor.", features: ["Güçlü vokal performans", "Elektrik gitar soloları", "Rock kraliçesi", "2.5 saat konser"], doorTime: "Konserden 2 saat önce", ageLimit: "+14 yaş", availability: 38 }
    // ... (VE DEVAMI - Tüm 143 event bu formatta devam edecek)
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { sharedEventsData };
}
